version: "3"

services:
  minecraft-spigot-sands:
    image: itzg/minecraft-server
    ports:
      - "25564:25565"
      - "8122:8123"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      TYPE: "SPIGOT"
      MEMORY: "1G"

