version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25567:25565"
      - "8125:8123"
    volumes:
      - "./minecraft-spigot-pc/data:/data"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      TYPE: "SPIGOT"
      Memory: "2G"

