version: "3"

services:
  minecraft-spigot-pc:
    image: itzg/minecraft-server
    ports:
      - "25567:25565"
      - "8125:8123"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      TYPE: "SPIGOT"
      MEMORY: "2G"

