version: "3"

services:
  minecraft-spigot-main:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "8124:8123"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      TYPE: "SPIGOT"
      MEMORY: "3G"
